import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Politique de confidentialité — BG EDITWORKS", description: "Politique de confidentialité de BG EDITWORKS." };

const sections = [
  ["01", "Responsable du traitement", <><p><strong>Bertrand Paul Emmanuel GEORGES EI</strong>, exploitant de BG EDITWORKS, est responsable du traitement des données transmises par e-mail, téléphone ou demande de devis.</p><p>Adresse professionnelle : 35 rue de la Gare, 18300 Veaugues, France. SIREN : 109 009 688 · SIRET : 109 009 688 00010.</p><p>Contact : <a href="mailto:bgeditworks@gmail.com">bgeditworks@gmail.com</a></p></>],
  ["02", "Données utilisées", <p>Nom ou entreprise, adresse e-mail, prestation recherchée, budget indicatif, délai, volume du projet, options choisies et contenu du message. Ne transmettez pas de données sensibles ni de fichiers confidentiels par un canal non convenu.</p>],
  ["03", "Finalités et bases légales", <p>Les données servent à répondre aux demandes, préparer une estimation ou un devis, exécuter une prestation et respecter les obligations administratives, fiscales et comptables. Les bases applicables sont les mesures précontractuelles, le contrat, l’intérêt légitime ou l’obligation légale selon le cas.</p>],
  ["04", "Destinataires et sécurité", <p>Les demandes sont destinées à BG EDITWORKS et, lorsque cela est nécessaire, aux prestataires techniques soumis à des obligations de confidentialité. Le site ne vend ni ne loue les données.</p>],
  ["05", "Durées de conservation", <p>Les demandes sans contrat sont conservées au maximum trois ans après le dernier contact. Les documents contractuels et comptables sont conservés pendant les durées légales applicables, notamment dix ans pour les pièces comptables.</p>],
  ["06", "Vos droits", <p>Vous pouvez demander l’accès, la rectification, l’effacement, la limitation, l’opposition ou la portabilité lorsque les conditions sont réunies. Écrivez à <a href="mailto:bgeditworks@gmail.com">bgeditworks@gmail.com</a>. Vous pouvez également saisir la <a href="https://www.cnil.fr/fr/adresser-une-plainte" target="_blank" rel="noreferrer">CNIL</a>.</p>],
  ["07", "Cookies et mises à jour", <p>Le site ne dépose actuellement aucun cookie publicitaire, de mesure d’audience ou de personnalisation. Cette politique sera mise à jour si les traitements ou les outils utilisés évoluent.</p>],
] as const;

export default function PrivacyPage() { return <main className="legal-page"><header className="legal-nav"><Link className="brand" href="/"><span>BG</span><b>EDITWORKS</b></Link><Link className="legal-back" href="/">← Retour au site</Link></header><section className="legal-hero"><p className="kicker">DONNÉES PERSONNELLES</p><h1>Politique de<br/><em>confidentialité.</em></h1><p>Une information claire sur les données transmises à BG EDITWORKS.</p></section><section className="legal-content">{sections.map(([n,title,content]) => <article key={n}><span>{n}</span><h2>{title}</h2>{content}</article>)}</section><footer className="legal-footer"><Link href="/">BG EDITWORKS</Link><p>Studio indépendant de post-production · <Link href="/mentions-legales">Mentions légales</Link></p></footer></main>; }
